# Continuous Integration (CI) build and publish to the artifact repository. On successful build and publish, the reusable deployment workflow is called.

name: Build

on:
  workflow_dispatch:
#  push:
#    branches:
#    - main

jobs:
  build:
    runs-on: [ubuntu-latest]
    
    permissions:
      contents: read
      id-token: write # Required for Google Workload Identity Federation

    outputs:
      # Output the artifact and the version so they can be passed to the deploy workflow
      built_version: ${{ steps.get-version.outputs.VERSION }}
      built_artifact: ${{ steps.get-artifact.outputs.ARTIFACT }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/gha-pool-webservices/providers/github-sdcote-webservices
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Get Maven project artifact
        id: get-artifact
        run: |
          ARTIFACT=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
          echo "ARTIFACT=$ARTIFACT" >> $GITHUB_OUTPUT
        working-directory: ${{ github.workspace }} # Ensure maven is run from the project root

      - name: Get Maven project version
        id: get-version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        working-directory: ${{ github.workspace }} # Ensure maven is run from the project root

      # Build and deploy the image to our docker registry, skipping integration tests
      - name: Build and push Docker image
        run: mvn -B -U clean install deploy -DskipITs --file pom.xml
        working-directory: ${{ github.workspace }}
        env:
          SPRING_PROFILES_ACTIVE: "github-actions"

  deploy_prod:
    needs: build
    permissions:
      id-token: write # Allow the called workflow to request OIDC tokens
      contents: read  # Often needed for actions/checkout in the called workflow even if you don't explicitly checkout there, good practice.
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      artifact: ${{ needs.build.outputs.built_artifact }}
      version: ${{ needs.build.outputs.built_version }}
      environment: PROD # Initially deploy into the PROD environment (for this demo)

# In an environment with several lower environments, this build workflow can have several jobs each depending on the successful 
# completion of the deployment (and test) of previous deployments into lower environments.
#
# It is not a good idea to use a workflow matrix here as a matrix will spawn multiple parallel jobs and we need to make sure the 
# lower environments pass before deploying to a higher environment.
#
#  deploy_dev:
#    needs: build
#    permissions:
#      id-token: write
#      contents: read
#    uses: ./.github/workflows/deploy.yml
#    secrets: inherit
#    with:
#      artifact: ${{ needs.build.outputs.built_artifact }}
#      version: ${{ needs.build.outputs.built_version }}
#      environment: TEST
#
#  deploy_test:
#    needs: deploy_dev
#    permissions:
#      id-token: write
#      contents: read
#    uses: ./.github/workflows/deploy.yml
#    secrets: inherit
#    with:
#      artifact: ${{ needs.build.outputs.built_artifact }}
#      version: ${{ needs.build.outputs.built_version }}
#      environment: TEST
#
#  deploy_qa:
#    needs: deploy_test
#    permissions:
#      id-token: write
#      contents: read
#    uses: ./.github/workflows/deploy.yml
#    secrets: inherit
#    with:
#      artifact: ${{ needs.build.outputs.built_artifact }}
#      version: ${{ needs.build.outputs.built_version }}
#      environment: QA
