# Continuous Integration (CI) build and publish to GCP Artifact Registry

name: Build

on:
  workflow_dispatch:
#  push:
#    branches:
#    - main

jobs:
  build:
    runs-on: [ubuntu-latest]
    
    permissions:
      contents: read
      id-token: write # Required for Google Workload Identity Federation

    outputs:
      # Output the artifact and the version so they can be passed to the deploy workflow
      built_version: ${{ steps.get-version.outputs.VERSION }}
      built_artifact: ${{ steps.get-version.outputs.ARTIFACT }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Debug GitHub Repository Context
        run: |
          echo "GitHub Repository Owner: ${{ github.repository_owner }}"
          echo "GitHub Repository Name: ${{ github.event.repository.name }}"
          echo "GitHub Repository Full: ${{ github.repository }}" 
          echo "GitHub Ref (Branch/Tag): ${{ github.ref }}"

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Test GCP Access Token with gcloud CLI
        run: |
          echo "--- Running gcloud auth print-access-token (default) ---"
          gcloud auth print-access-token || echo "Failed to print default access token"
          echo "--- Running gcloud auth print-access-token (impersonated) ---"
          gcloud auth print-access-token --impersonate-service-account="${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}" || echo "Failed to print impersonated access token"
          echo "--- gcloud config list ---"
          gcloud config list
          echo "--- gcloud auth list ---"
          gcloud auth list
        env:
          GCP_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Verify JIB_GOOGLE_CREDENTIALS_FILE Path
        run: |
          echo "Value of JIB_GOOGLE_CREDENTIALS_FILE: '${{ env.JIB_GOOGLE_CREDENTIALS_FILE }}'"
          # Verify the GOOGLE_GHA_CREDS_PATH env variable itself
          echo "Value of GOOGLE_GHA_CREDS_PATH: '${{ env.GOOGLE_GHA_CREDS_PATH }}'"

      - name: Check Credential File Existence and Content
        # !!! CAUTION: This will print part of your credential file to logs.
        # !!! ONLY FOR DEBUGGING. REMOVE IMMEDIATELY AFTER USE.
        run: |
          CRED_PATH="${{ env.GOOGLE_GHA_CREDS_PATH }}"
          echo "--- Checking file at: ${CRED_PATH} ---"
          ls -l "${CRED_PATH}" # Check existence, permissions
          file "${CRED_PATH}" # Check file type (should be JSON text)
          echo "--- First 10 lines of file: ---"
          head -n 10 "${CRED_PATH}" # Print first few lines to confirm JSON
          echo "--- Last 10 lines of file: ---"
          tail -n 10 "${CRED_PATH}" # Print last few lines
          echo "--- End of file check ---"

      - name: Get Maven project artifact
        id: get-artifact
        run: |
          ARTIFACT=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
          echo "ARTIFACT=$ARTIFACT" >> $GITHUB_OUTPUT
        working-directory: ${{ github.workspace }} # Ensure maven is run from the project root

      - name: Get Maven project version
        id: get-version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        working-directory: ${{ github.workspace }} # Ensure maven is run from the project root

      - name: Verify Maven System Properties
        run: |
          # Use 'mvn help:system' to print all system properties
          # Redirect output to a file, and print file content to logs
          mvn help:system -DoutputFile=system-properties.txt --f pom.xml
        working-directory: ${{ github.workspace }}
        env:
          # IMPORTANT: For this debug step, we must pass the variable so 'mvn help:system' sees it.
          JIB_GOOGLE_CREDENTIALS_FILE: ${{ env.GOOGLE_GHA_CREDS_PATH }}

      - name: Build and push Docker image
        # The 'deploy' phase will trigger Jib to build and push
        # run: mvn -B -U -X clean install deploy -Djib.google.credentials.file=${{ env.GOOGLE_GHA_CREDS_PATH }} --file pom.xml  # this does not work
        run: mvn -B -U -X clean install deploy --file pom.xml
        working-directory: ${{ github.workspace }}
        env:
          # Keep this here for the actual build step's execution
          # JIB_GOOGLE_CREDENTIALS_FILE: ${{ env.GOOGLE_GHA_CREDS_PATH }} # this does not work
          # GCP_SA_KEY_CONTENT: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON_KEY_CONTENT }} # this does not work
          SPRING_PROFILES_ACTIVE: "github-actions"

      - name: Call Deploy Workflow (Continuous Deployment)
        uses: ./.github/workflows/deploy.yml # Path to your reusable deploy workflow
        with:
          artifact: ${{ steps.get-version.outputs.ARTIFACT }} # Pass the name of the artifact to pull from the artifact registry
          version: ${{ steps.get-version.outputs.VERSION }} # Pass the version of the artifact
          secrets: inherit # Pass all secrets from this workflow to the called workflow

