# .github/workflows/deploy.yml
name: Deploy

on:
  workflow_dispatch:
    inputs:
      artifact:
        description: 'Name of the artifact to deploy'
        required: true
        type: string
        default: "webservices"
      version:
        description: 'Version to deploy'
        required: true
        type: string
        default: "0.0.1"
      service_name:
        description: 'Cloud Run service name'
        type: string
        default: "core-api"
  workflow_call:
    inputs:
      artifact:
        description: 'Artifact to deploy'
        required: true
        type: string
      version:
        description: 'Version to deploy'
        required: true
        type: string
      service_name:
        description: 'Cloud Run service name'
        type: string
        default: "core-api"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for Google Workload Identity Federation
      contents: read # Needed for actions/checkout if you include it, or other actions.

    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/gha-pool-webservices/providers/github-sdcote-webservices
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Show Workflow Call Inputs
        run: |
          echo "--- Workflow Dispatch Inputs ---"
          echo "Artifact: ${{ github.event.inputs.inputs.artifact }}"
          echo "Version: ${{ github.event.inputs.inputs.version }}"
          echo "Service Name: ${{ github.event.inputs.inputs.service_name }}"
          echo "--- End Workflow Call Inputs ---"
          echo "--- Workflow Call Inputs ---"
          echo "Artifact: ${{ github.event.workflow_call.inputs.artifact }}"
          echo "Version: ${{ github.event.workflow_call.inputs.version }}"
          echo "Service Name: ${{ github.event.workflow_call.inputs.service_name }}"
          echo "--- End Workflow Call Inputs ---"
          echo "" # For a newline separator in logs

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ github.event.inputs.service_name || github.event.workflow_call.inputs.service_name }}
          image: ${{ secrets.GCP_ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker/${{ github.event.inputs.artifact || github.event.workflow_call.inputs.artifact }}:${{ github.event.inputs.version || github.event.workflow_call.inputs.version }}
          region: us-east5
          # Optional: Specify a service account for the Cloud Run instance itself
          # service_account_email: webservices-sa@sdcote.iam.gserviceaccount.com

