# This is designed to check the stability of branches as part of pull requests.
# It performs a build, unit tests, and static analysis.

name: Verify

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  UnitTest:
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Checkout source
        uses: actions/checkout@v4.1.1

      - name: Build and Test with Maven
        run: mvn -B -U clean verify --file pom.xml
