name: Workflow2

on:
  workflow_call:
    inputs:
      artifact:
        description: 'The artifact name'
        required: true
        type: string
      version:
        description: 'The project version'
        required: true
        type: string

jobs:
  # ... jobs in workflow2.yml that use the inputs ...
  some_job:
    runs-on: ubuntu-latest
    steps:
      - name: Use inputs
        run: |
          echo "Received artifact: ${{ inputs.artifact }}"
          echo "Received version: ${{ inputs.version }}"