
name: Workflow1

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: [ubuntu-latest]
    
    permissions:
      contents: read

    outputs:
      # Output the artifact and the version so they can be passed to Workflow2
      built_version: ${{ steps.get-version.outputs.VERSION }}
      built_artifact: ${{ steps.get-artifact.outputs.ARTIFACT }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Get Maven project artifact
        id: get-artifact
        run: |
          ARTIFACT=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
          echo "ARTIFACT=$ARTIFACT" >> $GITHUB_OUTPUT
        working-directory: ${{ github.workspace }}

      - name: Get Maven project version
        id: get-version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        working-directory: ${{ github.workspace }}

      - name: Debug Build Job Outputs Before Call
        run: |
          echo "--- Build Job Outputs ---"
          echo "ARTIFACT: '${{ steps.get-artifact.outputs.ARTIFACT }}'"
          echo "VERSION: '${{ steps.get-version.outputs.VERSION }}'"
          echo "--- End Build Job Outputs ---"

  job2:
    needs: job1
    permissions:
      contents: read
    uses: ./.github/workflows/workflow2.yml
    secrets: inherit
    with:
      artifact: ${{ needs.job1.outputs.built_artifact }}
      version: ${{ needs.job1.outputs.built_version }}
