name: Workflow2

on:
  workflow_dispatch:
    inputs:
      artifact:
        description: 'Name of the artifact to deploy'
        required: true
        type: string
        default: "webservices"
      version:
        description: 'Version to deploy'
        required: true
        type: string
        default: "0.0.1"
      service_name:
        description: 'Cloud Run service name'
        type: string
        default: "core-api"
  workflow_call:
    inputs:
      artifact:
        description: 'The artifact name'
        required: true
        type: string
      version:
        description: 'The project version'
        required: true
        type: string
      service_name:
        type: string
        default: "core-api"

jobs:
  # ... jobs in workflow2.yml that use the inputs ...
  some_job:
    runs-on: ubuntu-latest
    steps:
      - name: Use inputs
        run: |
          echo "Received artifact: ${{ inputs.artifact }}"
          echo "Received version: ${{ inputs.version }}"
          echo "Service name: ${{ inputs.service_name }}"